package browser

import "testing"

// fixCp1251Mojibake repairs latin-1-misencoded cp1251 from ledongthuc/pdf.
// Inputs were generated by encoding "Программа тренировок" in cp1251 and
// reinterpreting each byte as a latin-1 codepoint — exactly the failure
// mode the library produces on Cyrillic-WinAnsi PDFs.
func TestFixCp1251Mojibake(t *testing.T) {
	cases := []struct {
		name, in, want string
	}{
		{
			name: "english unchanged",
			in:   "Training plan: 14 weeks",
			want: "Training plan: 14 weeks",
		},
		{
			name: "already cyrillic unchanged",
			in:   "Программа тренировок",
			want: "Программа тренировок",
		},
		{
			name: "empty unchanged",
			in:   "",
			want: "",
		},
		{
			// cp1251 bytes for "Программа" reinterpreted as latin-1.
			name: "cp1251 mojibake repaired",
			in:   "Ïðîãðàììà",
			want: "Программа",
		},
		{
			// Mixed: ASCII prefix + cp1251 cyrillic suffix.
			name: "mixed ascii+cp1251 repaired",
			in:   "Plan: Ïðîãðàììà",
			want: "Plan: Программа",
		},
		{
			// Latin-1 chars but below the 10-rune threshold → leave alone.
			name: "few latin1 runes left alone",
			in:   "café résumé",
			want: "café résumé",
		},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got := fixCp1251Mojibake(c.in)
			if got != c.want {
				t.Errorf("got %q, want %q", got, c.want)
			}
		})
	}
}
